/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
      Scanner keyboard = new Scanner(System.in);
      final int SIZE = 100 ;
      int [] no = new int[SIZE];
      String[] title = new String[SIZE];
      String[] explain = new String[SIZE];
      Date[] startDate = new Date[SIZE];
      Date[] endDate = new Date[SIZE];
      int[] total = new int[SIZE];
      int[] day = new int[SIZE];
      
   int count = 0;
      for(int i =0; i <SIZE;i++) {
    	  count++;
      
      System.out.print("번호?");
       no[i] = keyboard.nextInt();
       System.out.print("수업명?");
      title[i] = keyboard.nextLine();
       System.out.print("설명?");
       explain[i] = keyboard.nextLine();

       System.out.print("시작일?");
       startDate[i] = Date.valueOf(keyboard.next());
       System.out.print("종료일?");
       endDate[i] = Date.valueOf(keyboard.next());
       System.out.print("총수업시간?");
       total[i] = keyboard.nextInt();
       System.out.print("일수업시간?");
       day[i] = keyboard.nextInt();
       

       System.out.println();	
       System.out.print("계속 입력하시겠습니까? (Y/N) ");
       String response = keyboard.nextLine();
       if(!response.equalsIgnoreCase("y")) {
         break;
       }
       System.out.println();
      }
     
       for(int i = 0; i< count; i++) {
    	   System.out.printf("%d,%s,%s~%s,%d\n",no[i],title[i],startDate[i],endDate[i],total[i]);
    	   
       
       keyboard.close();
      }


      
   
}
}
