/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;

public class App {
   

    public static void main(String[] args) {
      Scanner keyboard = new Scanner(System.in);
      String no,name,explain,start,end,total,day;
      
      System.out.print("번호?");
       no = keyboard.nextLine();
       System.out.print("수업명?");
       name = keyboard.nextLine();
       System.out.print("설명?");
       explain = keyboard.nextLine();

       System.out.print("시작일?");
       start = keyboard.nextLine();
       System.out.print("종료일?");
       end = keyboard.nextLine();
       System.out.print("총수업시간?");
       total = keyboard.nextLine();
       System.out.print("일수업시간?");
       day = keyboard.nextLine();

       System.out.println();	



       System.out.printf("번호 : %s\n" ,no);
       System.out.printf("수업명:%s\n" , name);
       System.out.printf("설명:%s\n" , explain);
       System.out.printf("기간:%s ~ %s\n" ,start,end);
       System.out.printf("총수업시간:%s 시간\n" , total);
       System.out.printf("일수업시간:%s 시간\n" , day );
       
       keyboard.close();

      
    }
}
