/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.music;

import java.util.Scanner;

public class App {
	
    public static void main(String[] args) {
    	Scanner keyboard = new Scanner(System.in);
    	String name,artist,writer,genre;
    	int date;
    	System.out.printf("음악제목입력:");
    	name = keyboard.nextLine();
    	System.out.println("음악제목:"+name);
    	artist = keyboard.nextLine();
    	System.out.println("아티스트:"+artist);
    	date = keyboard.nextInt();
    	System.out.println("발매일:");
    	writer = keyboard.nextLine();
    	System.out.println("작곡:");
    	genre = keyboard.nextLine();
    	System.out.println("장르:");
    	
    }

}