/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        app classUnderTest = new app();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
